main: com.blockmart.shopgui.ShopGUI
name: ShopGUI
version: ${project.version}
api-version: 1.19
author: harsh
description: An economy shop GUI plugin.
softdepend: [Vault]
commands:
  shop:
    description: Opens the main shop GUI.
    usage: /shop
    permission: shopgui.command.shop
permissions:
  shopgui.command.shop:
    description: Allows opening the shop GUI.
    default: true
  shopgui.admin:
    description: Allows admin actions (e.g., adding/removing items).
    default: op
